import type { Metadata } from "next";

import "./globals.css";
import { ibmPlexSerif, montserrat } from "@/app/fonts";

import { Header } from "@/containers/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${ibmPlexSerif.variable} font-sans`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
